apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mx-us-east-2-p-cluster-1
  region: us-east-2
  version: 1.12

nodeGroups:
  - name: mx-us-east-2-p-cluster-1-ng-1
    labels: {role: workers}
    instanceType: c5.xlarge
    desiredCapacity: 2
    minSize: 1
    maxSize: 10
    volumeSize: 20
    privateNetworking: true
    ssh:
      publicKeyPath: /home/bob/id_rsa4096.pub
    iam:
      withAddonPolicies:
        autoScaler: true 